version: '3'
services:
  mysql:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  apache:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-apache
    ports:
      - '8888:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
